require 'rubygems'
require 'yaml'
require 'json'
require 'date'

def conformance_version(dir)
  require 'digest'
  Dir[File.join(dir, '*')].inject(Digest::SHA1.new){|digest, file| digest.update(Digest::SHA1.file(file).hexdigest) }
end

namespace :test do
  namespace :conformance do
    desc "Run conformance test suite"
    task :run do
      exec('mvn test')
    end
  end

  desc "Run conformance test suite"
  task :conformance => ['conformance:run'] do
  end
end

desc "Run conformance test suite"
task :test => ['test:conformance']
